name: build

on:
  push:
    # auto-update branches checked by created PR
    branches-ignore:
      - 'update/*'

  # only test check PR to master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: node18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install
        run: npm ci

      - name: typecheck
        run: npm run typecheck

      - name: build
        run: npm run build
